name: Release
on:
  push:
    tags:
      - "v*"

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      
      - name: Get Cargo package name
        id: get_name
        run: |
          PKG_NAME=$(cargo metadata --no-deps --format-version=1 \
                     | jq -r '.packages[0].name')
          echo "package_name=$PKG_NAME" >> $GITHUB_OUTPUT

      - name: Build (release)
        run: cargo build --release

      - name: Create Release
        id: create_release
        if: env.ACT != 'true'
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          draft: false
          prerelease: false

      - name: Upload Release Asset
        if: env.ACT != 'true'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/release/${{ steps.get_name.outputs.package_name }}
          asset_name: ${{ steps.get_name.outputs.package_name }}
          asset_content_type: application/octet-stream
